CKW-15
yeeezsh/CPE-KMUTT-Web pull request #13
Opened 2020-12-18 13:55 UTC by UnkAtreus

issue link: [CKW-15](createGlobalStyle)

2021-01-11 13:48 UTC, yee2542 requested changes

2021-01-11 13:48 UTC, yee2542 commented on frontend/src/common/components/Card/index.stories.tsx
> +  />
try to add `<div>`

2021-01-11 13:48 UTC, yee2542 commented on frontend/src/common/components/Card/index.stories.tsx
> +  />
add width or height on `<div>`

2021-01-11 13:48 UTC, yee2542 commented on frontend/src/common/components/Card/index.tsx
> +      <div className={['card-body', mode].join(' ')}>
please refactor `className` to component base
```tsx
<CardBodyStyled>
<CardBodyStyled/>
```

2021-01-11 13:48 UTC, yeeezsh commented on frontend/src/common/components/Card/styled.ts
> +  }
extract it to smaller components

2021-01-11 13:48 UTC, yee2542 commented on frontend/src/common/components/Card/types.ts
> +  primary?: boolean;
```ts
interface Base {
  picture: string;
  b: string;
}

interface A extends Partial<Base> {
    id: string
}
```

2021-01-11 13:48 UTC, yeeezsh commented on frontend/src/modules/root/components/whatNewSection/index.tsx
> +          />
should render from `constant`

2021-01-11 13:48 UTC, yeeezsh commented on frontend/src/modules/root/components/whatNewSection/styled.ts
> +  display: flex;
extract to smaller components

2021-01-14 22:47 UTC, yee2542 requested changes

2021-01-14 22:47 UTC, yee2542 commented on frontend/src/common/components/Card/index.tsx
> +        <div className="card-next" hidden={!props.primary}></div>
please change all className to `StyledComponents` code base

2021-01-16 18:46 UTC, nitpum requested changes

2021-01-16 18:46 UTC, nitpum commented on frontend/src/modules/root/components/whatNewSection/index.tsx
> +export default WhatNewSection;
Component's folder should be PascalCase 
`components/WhatNewSection/index.tsx`

2021-01-16 18:46 UTC, nitpum commented on frontend/public/images/whatNewSection_bg.svg
> +<!-- Generator: Adobe Illustrator 24.2.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
Remove this SVG in web is not require this info.
If I remember correct Adobe Illustrator have option to export SVG for web that remove unnecessary info

2021-01-17 14:29 UTC, nitpum commented on frontend/src/modules/root/page/Home/styled.ts
> +export const Main = styled.main``;
เอ อันนี้ไม่ใช้แล้วลบไหมครับ?

2021-01-17 14:29 UTC, nitpum commented on frontend/src/modules/root/page/Home/styled.ts
> +export const Main = styled.main``;
หมายถึงมันไม่ได้มี css อะไรเลยใช้ `<main>` ธรรมดาแทน

2021-01-17 14:31 UTC, nitpum commented on frontend/src/common/components/Card/types.ts
> +  primary?: boolean;
จริงๆ คิดว่าน่าจะใช้ variant มากกว่า primary นะ เพราะถ้ามี secondary หรืออื่น ๆ เข้ามาเงื่อนไขมันจะซ้อนกัน
```ts
variant: 'primary' | 'normal';
```

2021-01-17 14:32 UTC, nitpum commented on frontend/src/common/components/Card/types.ts
> +  primary?: boolean;
แต่ถ้าคิดว่าในอนาคตจะไม่มีอย่างอื่นนอกจาก primary ก็ใช้เป็น boolean ได้ แต่ดูๆ แล้วน่าจะมี

2021-01-17 15:39 UTC, UnkAtreus commented on frontend/src/common/components/Card/types.ts
> +  primary?: boolean;
![image](https://user-images.githubusercontent.com/50583924/104847852-c4266280-5914-11eb-8b69-0bc4cfd08d91.png)

ถ้าเขียน variant: 'primary' | 'normal'; มันขึ้น Error นี้อะคับผมหาวิธีแก้ไม่เจอ ไม่ก็ต้องเปลี่ยนรับ string แล้วไป filter เอาตอนเอาไปใช้

2021-01-21 13:16 UTC, yee2542 requested changes
please check

2021-01-21 13:16 UTC, yee2542 commented on frontend/public/css/styles.css
> +}
EOF

2021-01-21 13:16 UTC, yee2542 commented on frontend/src/common/components/Card/index.tsx
> +          backgroundImage: `url(${props.links})`,
Move this `div` to `StyledComponent` code base

2021-01-21 13:16 UTC, yee2542 commented on frontend/src/modules/root/components/WhatNewSection/index.tsx
> +            <div className="arrow-icon" />
same

2021-01-21 13:16 UTC, yee2542 commented on frontend/src/modules/root/components/WhatNewSection/index.tsx
> +        <div className="card-container">
same

2021-02-15 07:25 UTC, nitpum commented on frontend/src/common/components/Button/index.tsx
> +  );
ตรงนี้ระวังไป conflict กับ #19 นะครับ แนะนำถ้ารีวิวผ่านแล้วให้ merge PR นี้ก่อนนะครับ

2021-02-15 07:33 UTC, nitpum commented
เท่าที่ดูตอนนี้ไม่ติดอะไรแล้วครับ ส่วนใหญ่เห็นแก้ไปใน #19 แล้ว

2021-02-15 07:33 UTC, nitpum approved these changes

2021-03-12 09:42 UTC, yee2542 approved these changes

2021-03-12 09:42 UTC, yee2542 commented on frontend/src/common/components/Button/index.stories.tsx
> +    // color: { control: 'color' },
bad comment

2021-03-31 15:37 UTC, merged