CKW-7
yeeezsh/CPE-KMUTT-Web pull request #3
Opened 2020-11-12 09:27 UTC by UnkAtreus

related to : [CKW-7](https://cpe-kmutt-web.atlassian.net/browse/CKW-7)

2020-11-12 09:34 UTC, nitpum commented on frontend/src/common/utils/index.ts
> +};
ไม่ควรรวม utils เป็น object ครับมันจะทำ tree-shaking ไม่ได้ จะใช้อันไหนให้ import อันนั้นเอา

2020-11-12 09:34 UTC, nitpum commented on frontend/src/common/utils/index.ts
> +import { default as BREAKPOINTS } from './breakpoints';
ปล. ปกติเวลา import default จะใช้แบบนี้ครับ
```ts
import BREAKPOITINS from './breakpoints';
```

2020-11-12 09:34 UTC, nitpum commented on frontend/src/common/components/Container/styled.ts
> +import { default as VARIABLES } from '../../utils';
import ถ้าไฟล์ไม่ได้อยู่ใน folder เดียวกันห้ามใช้ relative path ครับ
ให้ใช้ absolute path แบบนี้
```ts
import VARIABLES from 'common/utils';
```

2020-11-12 09:35 UTC, nitpum requested changes

2020-11-12 09:35 UTC, nitpum commented on frontend/src/common/utils/index.ts
> +};
เช่นอยากใช้ color ก็ import ตรงๆ เลย 
```ts
import color from 'common/utils/colors`
```
จะใช้ breakpointd ก็ import ตรงๆ เลย
```ts
import breakpoint from 'common/utils/colors`
```

2020-11-12 09:40 UTC, nitpum requested changes, later dismissed

2020-11-12 09:40 UTC, nitpum commented on frontend/src/common/utils/breakpoints.ts
> +};
ดูแล้วไม่ใช่ `utils` ครับ แต่เป็น `constants` ย้ายไปไว้ที่
`src/common/constants/breakpoints.ts`

2020-11-12 09:40 UTC, nitpum commented on frontend/src/common/utils/colors.ts
> +};
ดูแล้วไม่ใช่ utils ครับ แต่เป็น constants ย้ายไปไว้ที่
`src/common/constants/colors.ts`

2020-11-12 09:43 UTC, nitpum commented on frontend/src/common/utils/index.ts
> +};
ถ้าเอามารวมกันมันทำ tree-shaking ไม่ได้ bundle size มันจะใหญ่ครับ ทำให้เว็บโหลดช้า

2020-11-12 09:46 UTC, nitpum commented on frontend/src/common/utils/breakpoints.ts
> +};
(ไม่เกี่ยวกับรีวิว) breakpoints เราต้องละเอียดขนาดนี้เลยเหรอ = =" 😅

2020-11-12 12:03 UTC, nitpum requested changes

2020-11-12 12:03 UTC, nitpum commented on frontend/src/common/components/Container/styled.ts
> +import BREAKPOINTS from 'src/common/constants/breakpoints';
โทษทีครับลืมตั้ง alias ให้ 
แก้เป็น `common/constants/breakpoints` ครับ

2020-11-12 12:10 UTC, nitpum commented on frontend/src/common/components/Container/styled.ts
> +import BREAKPOINTS from 'src/common/constants/breakpoints';
ลบ `src/` ออก

2020-11-13 06:52 UTC, yee2542 requested changes
please check

2020-11-13 06:52 UTC, yee2542 commented on frontend/src/common/components/Container/index.stories.tsx
> +} as Meta;
I'd like prefer to defined as a variable than type casting
```ts
const meta:Meta = { title, 'Common/Container', ...};
export default meta
```

2020-11-13 18:07 UTC, UnkAtreus commented on frontend/src/common/components/Container/styled.ts
> -  max-width: ${BREAKPOINTS.IPAD_LANDSCAPE};
เหมือนว่าใช้ ${BREAKPOINTS.IPAD_LANDSCAPE} แล้ว storybook จะ run ไม่ผ่าน

2020-11-14 05:59 UTC, nitpum commented on frontend/src/common/components/Container/styled.ts
> -  max-width: ${BREAKPOINTS.IPAD_LANDSCAPE};
ลองแล้วไม่มีปัญหานะครับ
'common/constants/breakpoints'

2020-11-14 09:48 UTC, UnkAtreus commented on frontend/src/common/components/Container/styled.ts
> -  max-width: ${BREAKPOINTS.IPAD_LANDSCAPE};
![image](https://user-images.githubusercontent.com/50583924/99144523-248cef80-2699-11eb-8c64-6fc91f26c913.png)
พอใช้ตัวนี้ Storybook ขึ้น error อย่างนี้อะครับ

2020-11-14 14:55 UTC, nitpum approved these changes

2020-11-14 15:10 UTC, nitpum approved these changes
LGTM 👍

2020-11-18 07:41 UTC, yee2542 approved these changes

2020-11-18 07:42 UTC, merged