[CKW-6] NavBar Component
yeeezsh/CPE-KMUTT-Web pull request #5
Opened 2020-11-13 08:29 UTC by PanpanPianchoopat

[CKW-6](https://cpe-kmutt-web.atlassian.net/browse/CKW-6)

2020-11-14 17:35 UTC, nitpum requested changes

2020-11-14 17:35 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/NavbarMenu.tsx
> +export default NavbarMenu;
แยกเป็นอีก component ไปเลยครับ 

ถ้า component นี้จะให้ component อื่นเรียกใช้ได้ด้วยให้เอาไว้แบบนี้
`src/modules/root/components/NavbarMenu/index.tsx`

แต่ถ้าให้เฉพาะ Navbar เป็นคนเรียกใช้อย่างเดียว เอาไว้ที่นี่ครับ
`src/modules/root/components/Navbar/components/NavbarMenu/index.tsx`

2020-11-14 17:35 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/styled.ts
> +  font-family: Sukhumvit Set;
น่าจะกำหนด fontFamily ไว้นะ ยังไงที่อื่นก็ต้องใช้ ไว้ที่ `src/common/styles/typography/fontFamily/index.ts`

```ts
enum FontFamily {
  Highlight: 'Sukhumvit Set' // จะใช้ชื่อว่า Highlight หรือ Default อะไรก็ว่าไป
}

export default FontFamily;
```
เวลาใช้ก็
```ts
import fontFamily from 'common/styles/typography/fontFamily'

2020-11-14 17:35 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/styled.ts
> +  font-family: Helvetica Neue;
อันนี้เหมือนกันครับ เอาไปใส่ไว้ใน `src/common/styles/typography/fontFamily/index.ts`

2020-11-14 17:35 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/styled.ts
> +  font-family: Helvetica Neue;
อันนี้เหมือนกันครับ เอาไปใส่ไว้ใน src/common/styles/typography/fontFamily/index.ts

2020-11-14 17:35 UTC, nitpum commented on frontend/src/common/models/Navbar/NavbarConstant.ts
> +import NavbarType from './NavbarType';
อันนี้ทำไมถึงเอาไฟล์นี้ไว้ที่ `model` อะครับ?

ส่วนตัวคิดว่าถ้าไม่ได้จะเอาไปใช้ที่อื่นเอาไฟล์นี้ไปไว้ในโฟลเดอร์ `components/Navbar` ได้เลย แล้วก็ตั้งชื่อไฟล์นี้ว่า `constants.ts`

ตัว `NavbarType` ก็เหมือนกันครับ

2020-11-14 17:35 UTC, nitpum commented on frontend/src/common/models/Navbar/NavbarType.ts
> +type NavbarType = {
ไฟล์นี้เหมือนกันครับ

2020-11-15 11:44 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/index.tsx
> +            overlayStyle={{ width: '100%', borderTop: '1px solid #eaeaea' }}>
เอาไปทำเป็น `StyledDropdown`(`styled.ts`) ไหมครับ จะได้ไม่ต้อง overlayStyle
```ts
import { Dropdown } from 'antd';

export const StyledDropdown = styled(Dropdown)`
  width: '100%';
  borderTop: '1px solid #eaeaea';
`
```
ปล. ตั้งชื่ออย่างอื่นก็ได้ที่สื่อความหมาย แต่ถ้านึกไม่ออกก็ StyledDropdown

2020-11-16 10:26 UTC, yee2542 commented
Please add this component into storybook

2020-11-16 10:27 UTC, yee2542 commented
Logo assets file should be in `public/assets/logo`

2020-11-17 19:02 UTC, nitpum requested changes

2020-11-17 19:02 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/index.tsx
> +            overlayStyle={{ width: '100%', borderTop: '1px solid #eaeaea' }}>
อันนี้ลืมลบหรือเปล่าครับ? หรือว่ามันบังคับใส่?

2020-11-17 19:02 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/styled.ts
> +//`;
ไม่ใช้แล้วลบคอมเม้นออกด้วยครับ เวลากลับมาทำทีหลังหรือคนอื่นมาทำต่อเขาจะได้ไม่ต้องมากังวลว่ามันลบได้ไหมหรือเก็บเอาไว้ทำไม

2020-11-17 19:02 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/styled.ts
> +
นี่ด้วยครับ

2020-11-17 19:02 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/styled.ts
> +
ไม่ใช้แล้วลบทิ้งเลยครับ คนอื่นมาทำต่อหรือเรามาทำเองทีหลังจะได้ไม่งงว่าเก็บเอาไว้ทำไม อีกอย่างเราใช้ Git อยู่แล้วถ้าจะเอากลับมาใช้สามารถย้อนมาดูได้ครับ

2020-11-17 19:02 UTC, nitpum commented on frontend/src/modules/root/components/Navbar/styled.ts
> +
นี่ด้วยครับ

2020-11-23 03:37 UTC, yee2542 commented
missing test

2021-01-02 15:02 UTC, yee2542 requested changes
please check,
if ready for review please tag ready to review again or ping me in slack

2021-01-02 15:02 UTC, yeeezsh commented on frontend/src/modules/root/components/Navbar/components/NavbarMenu/index.tsx
> +const NavbarMenu = (
missing type for `const NavbarMenu = ()` maybe add JSX element for that. I'm not sure what exactly type maybe `const Navbar: JSX.Element = ()` please try

2021-01-02 15:02 UTC, yee2542 commented on frontend/src/modules/root/components/Navbar/index.tsx
> +}
mvoe this line to another file `interface.ts` in the same `/components/Navbar/interface.ts`

2021-01-02 15:05 UTC, yee2542 commented on frontend/src/common/styles/typography/fontFamily/index.ts
> +  Default = 'Sukhumvit Set',
it change to `Kanit` for that and `Montserrat` for eng

2021-01-02 15:07 UTC, yee2542 commented on frontend/src/common/styles/typography/fontFamily/index.ts
> +  Default = 'Sukhumvit Set',
not sure check in `#design` in slack channel

2021-01-02 15:57 UTC, yee2542 requested changes
please check

2021-01-08 13:04 UTC, yee2542 commented on frontend/src/modules/root/components/Navbar/index.spec.tsx
> +});
```ts
  it('Should change visible to true when hamburger is clicked', () => {
    const wrapper = mount(<Navbar />);
    wrapper.find(Dropdown).at(0).simulate('click');
    const dropdownVisible = wrapper.find(Dropdown).prop('visible')?.valueOf();
    expect(dropdownVisible).toBeTruthy();
  });
```

2021-01-08 13:06 UTC, yee2542 commented on frontend/src/modules/root/components/Navbar/index.spec.tsx
> +});
also import 
```ts
import { Dropdown } from 'antd';
```

2021-04-20 16:30 UTC, nitpum approved these changes

2021-04-21 10:59 UTC, yee2542 requested changes
please check

2021-04-21 10:59 UTC, yee2542 commented on frontend/src/modules/root/components/Navbar/index.spec.tsx
> +  //});
dead code

2021-04-21 10:59 UTC, yee2542 commented on frontend/src/modules/root/page/Home/index.tsx
> +import Navbar from 'modules/root/components/Navbar/index';
this import look strange 
it should look like this `modules/root/components/Navbar`

2021-04-21 10:59 UTC, yee2542 commented on frontend/src/modules/root/components/Navbar/index.tsx
> +const Navbar: React.FC<NavBarProps> = () => {
this props is use for functionality ?
it seem `props.visible` is not using

2021-04-21 10:59 UTC, yee2542 commented on frontend/src/modules/root/page/Home/index.tsx
> +        <Navbar visible />
this navbar is receive `visible` for a props ?

2021-05-02 12:41 UTC, closed without merging